name: Docker image

on:
  push:
    branches:
      - main

jobs:
  # Build image and deploy to ghcr.io
  docker:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: |
          echo $PAT | docker login ghcr.io --username toothstone --password-stdin
        env:
          PAT: ${{ secrets.PACKAGE_REGISTRY_PAT }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/toothstone/cert-manager-anexia-webhook:latest .
      - name: Publish image
        run: |
          docker push ghcr.io/toothstone/cert-manager-anexia-webhook:latest
