name: Docker image

on:
  push:
    tags:
      - v*

jobs:
  # Build image and publish it
  docker:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: toothstone/cert-manager-webhook-anexia
          username: toothstone
          password: ${{ secrets.PACKAGE_REGISTRY_PAT }}
          strip_tag_prefix: v
          tag_with_latest: true
