name: Docker image

on:
  push:
    tags:
      - v*

jobs:
  # Build image and deploy to ghcr.io
  docker:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Login
        run: |
          echo $PAT | docker login ghcr.io --username toothstone --password-stdin
        env:
          PAT: ${{ secrets.PACKAGE_REGISTRY_PAT }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/toothstone/cert-manager-anexia-webhook:$VERSION .
      - name: Publish version image
        run: |
          docker push ghcr.io/toothstone/cert-manager-anexia-webhook:$VERSION
      - name: Tag latest image
        run: |
          docker tag ghcr.io/toothstone/cert-manager-anexia-webhook:$VERSION ghcr.io/toothstone/cert-manager-anexia-webhook:latest
      - name: Publish latest image
        run: |
          docker push ghcr.io/toothstone/cert-manager-anexia-webhook:latest
